api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: false
      trustedIPs:
        - 172.23.0.0/16

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: "LE_EMAIL"
      storage: "/letsencrypt/acme.json"
      # caServer: https://acme-v02.api.letsencrypt.org/directory # production (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging (testing)
      dnsChallenge:
        provider: cloudflare
        # delayBeforeCheck: 120
        # disablePropagationCheck: true # example provided gives A+ rating https://www.ssllabs.com/ssltest/
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

log:
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log"
  fields:
    defaultMode: keep
    headers:
      names:
        X-Forwarded-For: keep
experimental:
  plugins:
    cloudflarewarp:
      modulename: github.com/BetterCorp/cloudflarewarp
      version: v1.3.0
